### ISSUE TITLE
Cleaning JS errors in demo

### ISSUE THREAD

**Issue by micahcarroll** [HumanCompatibleAI/overcooked_ai#111]
Might be worthwhile trying to clean these errors at some point

<img width="586" alt="Screenshot 2023-02-03 at 5 36 45 PM" src="https://user-images.githubusercontent.com/11460267/216670115-83a77bb7-e535-4b12-90ee-fb64ed9fafc0.png">

**Comment by jyan1999** [comment]
Hmmm I don't think I am getting these errors. From the look of it you are missing some local files. Are these errors crashing the game or causing any problems?

**Comment by micahcarroll** [comment]
Ah, i think that may be why the game is not working for me. Will try to delete the whole folder and set up from scratch!

**Comment by jyan1999** [comment]
I think some of these warnings (babel.min.js one for example) are caused by the missing js lib folder, which I have added by pushing an update to the branch. 

The last warning about favicon.ico is different though since I can see that the server/static directory does have this file. I'll keep looking to see what might have caused this.
