### ISSUE TITLE
Default Recipe config

### ISSUE THREAD

**Issue by bmielnicki** [HumanCompatibleAI/overcooked_ai#56]
Currently when recipe config is not specified user gets an error `ValueError: Recipe class must be configured before recipes can be created`.
The fix for this is to insert `Recipe.configure ({})` somewhere in the code that does not add any additional information except the will of the user to prevent error. I would like to do something that won't force user to add `Recipe.configure ({})` in the code without sacrificing the positives of the current solution.
Why this check was added? There is anything wrong with assuming that if recipes are not configured user chose to have a default configuration (maybe with adding some warning print)?

**Comment by akbir** [comment]
So this is also a problem when it comes to serialising and unserializing the environment for python multi-processing. Would be keen to understand how to get past this too.

**Comment by micahcarroll** [comment]
The best person for this would be @nathan-miller23, but I don't know if he'll see this (as he's not actively involved in maintenance anymore). I currently don't have a lot of time to look into this, but (hopefully) soon we'll have an engineer working on the repo, and I'll direct them to this.

@akbir if you find a fix in the meantime, feel free to make a PR. I'm guessing that since the env works with rllib, they have some way of doing the serializing that works?
