### ISSUE TITLE
Put overcooked-demo inside of overcooked_ai repo, run overcooked-demo code in test workflow

### ISSUE THREAD

**Issue by bmielnicki** [HumanCompatibleAI/overcooked_ai#58]
To prevent making overcooked-demo code outdated. Starting a container should be big improvement here (now there is no warning that changes here broke overcooked-demo i.e. its not even starting).

**Comment by micahcarroll** [comment]
This is a great idea!

@nathan-miller23 @mesutyang97 one thing me and Mesut were talking about is that it might make sense to turn overcooked-demo into a submodule of overcooked-ai.

The main change it would require would be to also have a way to run the overcooked-demo docker commands (e.g. `./up.sh`) from any location (without being in the repo directory itself): otherwise, if one installs `overcooked-ai` with `pip` and then attempts to use `overcooked-demo`, they would have to find the folder where overcooked-demo was installed by pip, and run the docker commands there, that seems quite absurd.

If this is something that you would want to work on @bmielnicki, this would be really useful! I think making overcooked-demo a submodule might also help (or at least is relevant) for completing this specific issue.

**Comment by bmielnicki** [comment]
I would gladly help with this! Doing this would make solving this issue quite easily.

This seems doable in those steps:
1. Put overcooked-demo into a subdirectory of overcooked_ai.
2. Add to package_data om setup.py overcooked-demo directory.
3. By having a directory package in static.py we can get the path of up.sh. Now we can have a python script that runs up.sh `python overcooked-demo.py up.sh` or return path to up.sh `python overcooked-demo-path.py up.sh`. The former can be tricky as by default sudo is required to run docker container (user need to copy one line of bash (for more detailed info see https://askubuntu.com/questions/477551/how-can-i-use-docker-without-sudo ) that allows running docker without sudo), later is easy, but inconvenient (you need to run python script to copy sh file path and run it with sudo). It seems not that time consuming to do both.

**Comment by micahcarroll** [comment]
I would wait on @nathan-miller23 to confirm that this way of approaching the merge makes most sense – I just talked with @mesutyang97 and we seem to be on the same page.

**Comment by micahcarroll** [comment]
One thing to figure out here is how to integrate everything into one repo without bloating it excessively in terms of installation (or even cloning it): we don't want people to have to download hundreds of megabytes for a simple environment, or have to install the DRL code (with all it's dependencies) unless they choose to do so.

Some libraries that I know of that seem to handle this kind of usage are `ray` (which you can install with or without `rllib` for example). We might want to copy their structure, or generally compare with other approaches that exist out there.
